### PR TITLE
in 19, the RANDOM is rand, and uniform_s 2nd argument is to be ?SEED,…

### PR DESCRIPTION
**Pull request by getong**
… which would change as version detected.
@mrallen1 I think the argument should be ?SEED.
I make a pr to exometer_core, see  Feuerlabs/exometer_core#94. And I found the log fail, and finally I debug this should be the reason.

### CODE REVIEW

**Comment by jadeallenx** [comment]
Yes, you're right that `rand` and `random` states are incompatible. Good catch! 

Since the NewState that's generated is discarded, perhaps there's no need to use `random_s` here at all?  Can you clarify your intention in using the timestamp @joewilliams?

**Comment by joewilliams** [comment]
I think @russelldb added this code (5yrs ago 🤣 ) perhaps he can recall why `Now` was used.

**Comment by jadeallenx** [comment]
Oh my gosh! 😆 I think @getong should just make it `?RANDOM:uniform` and call it a day.

**Comment by getong** [comment]
The `random` module produces the same result in the first call in different process calls, it is not random at all. So different seed must be used, in this case, it uses the timestamp.
We can test it in open a erl proces
``` shell
erl
1> random:uniform().
0.4435846174457203
```
Every time we launch erl process, and call the `random:uniform()`, it produces the value:
`0.4435846174457203`
The `rand` module tends to solve this problem. It produces different values in the first call in different process calls. With or without seed, it can still produces random values.

**Comment by joewilliams** [comment]
@getong 👍  are there any tests we should add to this PR along these lines?

**Comment by getong** [comment]
@joewilliams  I have checked the test code, it just not check the `slide_uniform` method.  A bit work need to be done. I will do it in near few days.

**Comment by getong** [comment]
@mrallen1  I put this branch into Feuerlabs/exometer_core#94, for test purpose, and found the random module error, the first time use ?SEED is return `undefined`, so I change the `SEED` to be 
```
-define(SEED, fun() ->
                      case random:seed(os:timestamp()) of
                          undefined ->
                              random:seed(os:timestamp());
                          State ->
                              State
                      end
              end
       ).
```

But I don't know why it not work.
Need help.

**Comment by jadeallenx** [comment]
```diff
diff --git a/include/folsom.hrl b/include/folsom.hrl
index 2d48c7f..0b770dc 100644
--- a/include/folsom.hrl
+++ b/include/folsom.hrl
@@ -18,7 +18,7 @@
 -ifdef(use_rand).
 -define(SEED, rand:seed(exsplus)).
 -else.
--define(SEED, random:seed(os:timestamp())).
+-define(SEED, os:timestamp()).
 -endif.
```

This patch works.

`random:seed/1` returns its previous state, but we don't care about the previous state, we just care about the literal seed value. If you look through the code, the only places where the `seed` field is used in the records from the folsom.hrl file, is calls to `uniform_s/2` so we just need a literal seed value - for the `rand` module, that literal seed value has to come from the `rand:seed/1` function call. For the `random` module, it's fine to just use the output of `os:timestamp()` directly because `random:uniform_s/2` will "do the right thing" with that seed value.

I believe this solves the problem.  It would be lovely if we had a unit test for this though - would give a lot more confidence 😄

**Comment by jj1bdx** [comment]
I guess you've already know this, but rand module functions do not need explicit seeding.

**Comment by jadeallenx** [comment]
Yeah, except we have to support both modules so, this is the easiest thing to do for now. 😛

**Comment by getong** [comment]
@mrallen1 Thanks, all the tests are passed.
@joewilliams I rebase the pr, I believe the code can be merged now.

**Pull request merged**
