### PR TITLE
Prevent races on metric ETS tables creation

### LINKED ISSUE #2: pids and ets ids leaks
``` erlang
3> f(Pid1), f(Pid2), [Pid1, Pid2] = [erlang:spawn_link(fun() -> receive _ -> ok = folsom_metrics:new_histogram(<<"sorry">>, slide) end end) || _ <- lists:seq(1, 2)].
[<0.45.0>,<0.46.0>]
4>  Pid1 ! Pid2 ! sorry.
sorry
5> supervisor:which_children(folsom_sample_slide_sup).
[{undefined,<0.49.0>,worker,[folsom_sample_slide_server]},
 {undefined,<0.50.0>,worker,[folsom_sample_slide_server]}]
7> ets:tab2list(folsom_histograms).
[{<<"sorry">>,
  {histogram,slide,{slide,1028,20506,<0.50.0>}}}]
```

I expected that there would be only one child of folsom_sample_slide_sup. So the second child and its  ets are leaked.

``` erlang
supervisor:count_children(folsom_sample_slide_sup) =/= erlang:length(ets:tab2list(folsom_histograms)).
```

metrics with the same leaks:
- history
- spiral
- duration

### PR DESCRIPTION
**Pull request by puzza007**
Fixes #2

If you're creating a lot of metrics this could be a performance concern. I'm not sure how people use it in general but I'm usually creating metrics on the fly for e.g. HTTP status codes, where the number is limited.

### CODE REVIEW

**Comment by joewilliams** [comment]
This looks reasonable to me, thanks for adding tests. It doesn't *seem* like it breaks any APIs.

@russelldb I think you worked on much of the original code, if you have time do you mind also reviewing?

**Comment by russelldb** [comment]
If you're ok to wait until GMT Saturday lunchtime (~18) I can look at it then?

**Comment by joewilliams** [comment]
@russelldb no rush, thank you!

**Comment by puzza007** [comment]
Thanks guys. No hurry.

**Comment by russelldb** [comment]
Sorry, I missed this last weekend. Will be reviewing this weekend coming.

**Comment by joewilliams** [comment]
@russelldb just a friendly reminder to review when you have time. ❤️

**Comment by joewilliams** [comment]
@russelldb do you have time to take a look at this one?

**Pull request merged**
